//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd.Source {
    
    
    public partial class HotelDetail {
        
        /// <summary>
        /// usrHotelImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FrontEnd.Source.usrHotelDetail.usrHotelImage usrHotelImage;
        
        /// <summary>
        /// usrHotelDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FrontEnd.Source.usrHotelDetail.usrHotelDetail usrHotelDetail;
        
        /// <summary>
        /// usrHotelIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FrontEnd.Source.usrHotelDetail.usrHotelIntroduction usrHotelIntroduction;
        
        /// <summary>
        /// usrCheckIn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FrontEnd.Source.usrHotelDetail.usrCheckIn usrCheckIn;
    }
}
